name: Merge Deploy

on:
  push:
    branches: ["main"]

permissions:
  contents: read
  deployments: write

jobs:
  deployment-check:
    name: Deployment Check
    runs-on: ubuntu-latest
    outputs:
      continue: ${{ steps.deployment-check.outputs.continue }}
      sha: ${{ steps.deployment-check.outputs.sha }}
    steps:
      - name: deployment check
        id: deployment-check
        uses: github/branch-deploy@97edad089bbbe0c0ad13db7bf9ac085eaa47e255 # v12.0.1
        with:
          merge_deploy_mode: true
          environment: prod

  deploy:
    name: Deploy
    if: ${{ needs.deployment-check.outputs.continue == 'true' }}
    needs: deployment-check
    runs-on: ubuntu-latest
    environment: prod
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_ENDPOINT_URL_S3: ${{ secrets.AWS_ENDPOINT_URL_S3 }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      UNIFI_API_KEY: ${{ secrets.UNIFI_API_KEY }}
      UNIFI_CLOUD_CONNECTOR: ${{ secrets.UNIFI_CLOUD_CONNECTOR }}
    defaults:
      run:
        shell: "nix develop --impure -c bash -e {0}"
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          ref: ${{ needs.deployment-check.outputs.sha }}
          fetch-depth: 1
          persist-credentials: false

      - name: Nix Flake
        uses: cachix/install-nix-action@13d8dd58da0234aa297dedd986986ccb8e7f3e24 # v31.11.1
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Tofu Init
        run: |
          tofu init -input=false

      - name: Tofu Apply
        run: |
          tofu apply -input=false -no-color -compact-warnings
