name: Unlock on Merge

on:
  pull_request:
    types: [closed]

permissions:
  contents: write

jobs:
  unlock-on-merge:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true

    steps:
      - name: Unlock on Merge
        uses: github/branch-deploy@97edad089bbbe0c0ad13db7bf9ac085eaa47e255 # v12.0.1
        with:
          unlock_on_merge_mode: true
          environment_targets: prod
